---
title: "02_tabulate-data"
author: "Nina Rynne"
date: "2023-03-24"
output: html_document
---

```{r setup, include=FALSE}

# Set up R Markdown options
knitr::opts_chunk$set(echo = FALSE)

```

```{r libraries}

# Libraries used
# -------------------------------------------------------
library(tidyr)
library(dplyr)
library(here)
library(stringr)
library(forcats)
library(qualV)
library(topmodel)
library(Metrics)
library(sf)

```

```{r arguments}

# Parameters for File and Data Management
# -------------------------------------------------------

# Load lists of parameters from CSV files
esms <- unlist(read.csv(here("data/parameters/esms.csv"), header = FALSE))
mems <- unlist(read.csv(here("data/parameters/mems.csv"), header = FALSE))
element <- unlist(read.csv(here("data/parameters/type.csv"), header = FALSE))
element_long <- unlist(read.csv(here("data/parameters/type_longname.csv"), header = FALSE))
obs <- unlist(read.csv(here("data/parameters/observations.csv"), header = FALSE))

```

```{r load}

# Load Model Output and Reconstructed Catch Yearly Data
# -------------------------------------------------------
modeloutputs_byYear <- read.csv(here("output/modeloutputs_yearly.csv"))
reconstructedWAT_byYear_global <- read.csv(here("output/reconstructedcatch_WAT_global.csv"))
reconstructedSAU_byYear_global <- read.csv(here("output/reconstructedcatch_SAU_global.csv"))
reconstructedWAT_byYear_LME <- read.csv(here("output/reconstructedcatch_WAT_LME.csv"))

# Load Global Shapefile
lme_shapefile = st_read(here("data/shapefile/LMEs66.shp")) 

```

```{r normalised}

# Normalise Underlying Data
# This section normalises the modelled and observed total catch data
# for further analysis. Data is normalised against the first 5 years
# -------------------------------------------------------

# Normalise Global Level Data
tc_byYear_withWAT_global_norm <- modeloutputs_byYear %>%
  filter(Element == "tc_tonnes_year") %>% # only total catch
  filter(LME == "0") %>% # only global level data
  left_join(reconstructedWAT_byYear_global, by = join_by(LME, Year)) %>% # add Watson observations
  mutate("Model" = paste(MEMs, ESMs)) %>% # create column for MEM & ESM ID combined
  # normalise total catch observations against first 5 years (starting 1971 for CMIP5, 1950 for CMIP6)
  group_by(Model) %>%
  mutate(obs_start = mean(rec_obs[between(Year, min(Year), min(Year)+4)]),
         rec_obs_norm = 100*(rec_obs - obs_start)/obs_start) %>%
  # normalise total catch projections against first 5 years (starting 1971 for CMIP5, 1950 for CMIP6)
  mutate(proj_start = mean(Value[between(Year, min(Year), min(Year)+4)]),
         proj_tc_norm = 100*(Value - proj_start)/proj_start)

# Normalise LME Level Data
tc_byYear_withWAT_LME_norm <- modeloutputs_byYear %>%
  filter(Element == "tc_tonnes_year") %>% # only total catch
  filter(LME !=0) %>% # only LME level data
  left_join(reconstructedWAT_byYear_LME, by = join_by(LME, Year)) %>% # add Watson observations
  mutate("Model" = paste(MEMs, ESMs)) %>% # create column for MEM & ESM ID combined
  # normalise total catch observations against first 5 years (starting 1971 for CMIP5, 1950 for CMIP6)
  group_by(LME, Model, Source) %>%
  mutate(obs_start = mean(rec_obs[between(Year, min(Year), min(Year)+4)]),
         rec_obs_norm = 100*(rec_obs - obs_start)/obs_start) %>%
  # normalise total catch projections against first 5 years (starting 1971 for CMIP5, 1950 for CMIP6)
  mutate(proj_start = mean(Value[between(Year, min(Year), min(Year)+4)]),
         proj_tc_norm = 100*(Value - proj_start)/proj_start)


# Combine and Normalise Reconstructed Observations Data
obs_tc_byYear_global_norm <- rbind(reconstructedSAU_byYear_global, reconstructedWAT_byYear_global) %>%
  group_by(LME, Source) %>%
  mutate(obs_start = mean(rec_obs[between(Year, min(Year), min(Year)+4)]),
                rec_obs_norm = 100*(rec_obs - obs_start)/obs_start)


```


```{r LME_stats_function}

# Calculate Statistical Metrics Function LME Level

# Function Name: getLMEstats
# This function calculates statstical metrics by LME/MEM/ESM
# @param: mem_name Marine Ecosystem Model, a character
# @param: esm_name Earth System Model, a character
# @return: a dataframe of statistical metrics by LME/MEM/ESM
# -------------------------------------------------------

getLMEStats <- function(mem_name, esm_name) {
  
    # Loop through all 66 LMEs, filtering by MEM & ESM
    for(k in 1:66) {
      LMEstats <- tc_byYear_withWAT_LME_norm %>%
        filter(MEMs == mem_name,
               ESMs == esm_name,
               LME == k)
      
      # Create a vector of results for specified LME/MEM/ESM
      LMEstats_vector <- data.frame("MEMs" = mem_name,
                                    "ESMs" = esm_name,
                                    "Variable" = "tc_byYear",
                                    "LME" = k,
                                    "NAME" = unique(LMEstats$NAME),
                                    "Model" = unique(LMEstats$Model),
                                    "Correlation" = cor(LMEstats$rec_obs_norm, LMEstats$proj_tc_norm),
                                    "RMSE" = rmse(LMEstats$rec_obs_norm, LMEstats$proj_tc_norm),
                                    "AAE" = mae(LMEstats$rec_obs_norm, LMEstats$proj_tc_norm),
                                    "Bias" = bias(LMEstats$rec_obs_norm, LMEstats$proj_tc_norm),
                                    "ReliabilityIndex" = GRI(LMEstats$rec_obs_norm, LMEstats$proj_tc_norm),
                                    "ModellingEfficiency" = NSeff(LMEstats$rec_obs_norm, LMEstats$proj_tc_norm)
                                    )
      
      # Create Dataframe for Results, or Append if Exists
      if(!exists("LMEstats_table")) {
        LMEstats_table <- LMEstats_vector
      }else{
        LMEstats_table <- rbind(LMEstats_table, LMEstats_vector)
      } # End if/else loop

    } # End for loop
 
   return(LMEstats_table)
   
  } # End function

```

```{r global_stats_function}

# Calculate Statistical Metrics Function Global Level

# Function Name: getGlobalStats
# This function calculates statstical metrics by MEM/ESM on global level data
# @param: mem_name Marine Ecosystem Model, a character
# @param: esm_name Earth System Model, a character
# @return: a dataframe of statistical metrics by MEM/ESM
# -------------------------------------------------------

getGlobalStats <- function(mem_name, esm_name) {

  # Filtering by MEM & ESM
  globalstats <- tc_byYear_withWAT_global_norm %>%
    filter(MEMs == mem_name,
           ESMs == esm_name,
           Element == "tc_tonnes_year",
           LME == "0") 
  
  # Create a vector of results for specified MEM/ESM
  globalstats_vector <- data.frame("MEMs" = mem_name,
                                   "ESMs" = esm_name,
                                   "Variable" = "tc_byYear",
                                   "NAME" = "Global",
                                   "Model" = unique(globalstats$Model),
                                   "Correlation" = cor(globalstats$rec_obs_norm, globalstats$proj_tc_norm),
                                   "RMSE" = rmse(globalstats$rec_obs_norm, globalstats$proj_tc_norm),
                                   "AAE" = mae(globalstats$rec_obs_norm, globalstats$proj_tc_norm),
                                   "Bias" = bias(globalstats$rec_obs_norm, globalstats$proj_tc_norm),
                                   "ReliabilityIndex" = GRI(globalstats$rec_obs_norm, globalstats$proj_tc_norm),
                                   "ModellingEfficiency" = NSeff(globalstats$rec_obs_norm, globalstats$proj_tc_norm)
                                   )
  
  return(globalstats_vector)
  
  } # end function

```

```{r call_LME_stats_function}

# Call Statistical Metrics Function LME Level
# -------------------------------------------------------

for(i in 1:length(mems)){
  for(j in 1:length(esms)){
    
    LMEstats_return <- getLMEStats(mem_name = mems[i],
                                   esm_name = esms[j])
    
    # decide how to handle data returned from function
    
    if(!exists("stats_byLME_byModel_norm")){
        stats_byLME_byModel_norm <- LMEstats_return
      }else{
        stats_byLME_byModel_norm <- rbind(stats_byLME_byModel_norm, LMEstats_return)
      } # end if/else loop

  } # end esm loop
  } # end mem loop

```

```{r call_global_stats_function}

# Call Statistical Metrics Function Global Level
# -------------------------------------------------------

for(i in 1:length(mems)){
  for(j in 1:length(esms)){
    
    globalstats_return <- getGlobalStats(mem_name = mems[i],
                                  esm_name = esms[j])
    
    # decide how to handle data returned from function
    
    if(!exists("stats_global_byModel_norm")){
        stats_global_byModel_norm <- globalstats_return
      }else{
        stats_global_byModel_norm <- rbind(stats_global_byModel_norm, globalstats_return)
      } # end if/else loop

  } # end esm loop
  } # end mem loop

```

```{r stats_shapefile}

# Apply Standard Shapefile to LME Level Statistics
# -------------------------------------------------------
stats_byLME_shaped_norm <- merge(
  lme_shapefile,
  stats_byLME_byModel_norm,
  by.y = "NAME",
  by.x = "LME_NAME")

```


```{r save}

# Save Datafiles for Plotting
# -------------------------------------------------------

# modelled and observed catch by year, globally
saveRDS(object = tc_byYear_withWAT_global_norm, file = here("output/tc_byYear_withWAT_global_norm.rds"))

# modelled and observed catch by year, by LME
saveRDS(object = tc_byYear_withWAT_LME_norm, file = here("output/tc_byYear_withWAT_LME_norm.rds"))

# statistical test results by LME
saveRDS(object = stats_byLME_byModel_norm, file = here("output/stats_byLME_byModel_norm.rds"))

# statistical test results, globally
saveRDS(object = stats_global_byModel_norm, file = here("output/stats_global_byModel_norm.rds"))

# statistical test results by LME, adjusted for shape file to use for map plots
saveRDS(object = stats_byLME_shaped_norm, file = here("output/stats_byLME_shaped_norm.rds"))

# observed values only, WAT and SAU 
saveRDS(object = obs_tc_byYear_global_norm, file = here("output/obs_tc_byYear_global_norm.rds"))

```

```{r export}

# Export Statistics at Global Level for Manuscript
# -------------------------------------------------------
write.csv(stats_global_byModel_norm, here("output/globalstats.csv"), row.names = TRUE)

```
